<?xml version="1.0" encoding="utf-8"?><Database Class="DataClasses1DataContext" Serialization="Unidirectional" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="" Member="filiere">
    <Type Name="filiere">
      <Column Member="id_filiere" Type="System.String" CanBeNull="false" />
      <Column Member="nom_filiere" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
</Database>