//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Personne", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class Personne : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrenomField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenom {
            get {
                return this.PrenomField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenomField, value) != true)) {
                    this.PrenomField = value;
                    this.RaisePropertyChanged("Prenom");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Bonjour", ReplyAction="http://tempuri.org/IService1/BonjourResponse")]
        string Bonjour(string n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Bonjour", ReplyAction="http://tempuri.org/IService1/BonjourResponse")]
        System.Threading.Tasks.Task<string> BonjourAsync(string n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFiliers", ReplyAction="http://tempuri.org/IService1/GetFiliersResponse")]
        System.Data.DataTable GetFiliers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFiliers", ReplyAction="http://tempuri.org/IService1/GetFiliersResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetFiliersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DescriptionPersonne", ReplyAction="http://tempuri.org/IService1/DescriptionPersonneResponse")]
        string DescriptionPersonne(App.ServiceReference.Personne p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DescriptionPersonne", ReplyAction="http://tempuri.org/IService1/DescriptionPersonneResponse")]
        System.Threading.Tasks.Task<string> DescriptionPersonneAsync(App.ServiceReference.Personne p);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : App.ServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<App.ServiceReference.IService1>, App.ServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Bonjour(string n) {
            return base.Channel.Bonjour(n);
        }
        
        public System.Threading.Tasks.Task<string> BonjourAsync(string n) {
            return base.Channel.BonjourAsync(n);
        }
        
        public System.Data.DataTable GetFiliers() {
            return base.Channel.GetFiliers();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetFiliersAsync() {
            return base.Channel.GetFiliersAsync();
        }
        
        public string DescriptionPersonne(App.ServiceReference.Personne p) {
            return base.Channel.DescriptionPersonne(p);
        }
        
        public System.Threading.Tasks.Task<string> DescriptionPersonneAsync(App.ServiceReference.Personne p) {
            return base.Channel.DescriptionPersonneAsync(p);
        }
    }
}
